# Generated by Django 5.1.3 on 2024-11-22 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0002_alter_course_description"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_pay", models.DateField(verbose_name="Дата оплаты")),
                ("summ", models.PositiveIntegerField(verbose_name="Сумма")),
                (
                    "pay_type",
                    models.CharField(
                        choices=[
                            ("cash", "Наличные"),
                            ("no-cash", "Безналичная оплата"),
                        ],
                        default="cash",
                        max_length=10,
                        verbose_name="Тип платежа",
                    ),
                ),
                (
                    "pay_course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lms.course",
                        verbose_name="Оплаченный курс",
                    ),
                ),
                (
                    "pay_lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lms.lesson",
                        verbose_name="Оплаченный курс",
                    ),
                ),
                (
                    "user_pay",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Платеж",
                "verbose_name_plural": "Платежи",
            },
        ),
    ]
