# Generated by Django 5.1.3 on 2024-11-24 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_payments_pay_course_alter_payments_pay_lesson"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payments",
            name="user_pay",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pays",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
    ]
