# Generated by Django 5.1.3 on 2024-12-06 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_payments_user_pay"),
    ]

    operations = [
        migrations.AddField(
            model_name="payments",
            name="payment_link",
            field=models.CharField(
                blank=True, max_length=350, null=True, verbose_name="Ссылка на оплату"
            ),
        ),
        migrations.AddField(
            model_name="payments",
            name="session_id",
            field=models.CharField(blank=True, null=True, verbose_name="id сессии"),
        ),
    ]
