# Generated by Django 5.1.3 on 2024-12-06 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0006_subscription"),
        ("users", "0005_payments_payment_link_payments_session_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payments",
            name="pay_course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payment_courses",
                to="lms.course",
                verbose_name="Оплаченный курс",
            ),
        ),
        migrations.AlterField(
            model_name="payments",
            name="pay_lesson",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payment_lesson",
                to="lms.lesson",
                verbose_name="Оплаченный курс",
            ),
        ),
    ]
