# Generated by Django 5.1.3 on 2024-12-06 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_payments_pay_course_alter_payments_pay_lesson"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payments",
            name="payment_link",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="Ссылка на оплату"
            ),
        ),
    ]
