# Generated by Django 5.1.3 on 2024-11-19 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Course Description",
                null=True,
                verbose_name="Описание курса",
            ),
        ),
    ]
