# Generated by Django 5.1.3 on 2024-11-23 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0003_alter_lesson_course"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="preview",
            field=models.ImageField(
                blank=True,
                default="lms/courses/default.jpg",
                help_text="Course Preview",
                null=True,
                upload_to="lms/courses/",
                verbose_name="Превью курса",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="preview",
            field=models.ImageField(
                blank=True,
                default="lms/lessons/default.jpg",
                help_text="Lessons Preview",
                null=True,
                upload_to="lms/lessons/",
                verbose_name="Превью урока",
            ),
        ),
    ]
